### ISSUE TITLE
Schema plugin build failure

### ISSUE THREAD

**Issue by scgordon** [metadata101/iso19115-3#25]
I'm building a 3.3.0 version of GeoNetwork, and attempting to add schema plugins. To learn how, I've decided to follow the instructions for adding ISO19115-3 from this repository.

There is a print out below of what occurs when I attempt to build after implementing the instructions. I have also tried this process with other branches but get the same results.

I have one question about the instructions. What is the difference between the web module in web/pom.xml and the webapp in web/pom.xml in the following two steps?

"Add the dependency in the web module in web/pom.xml:

<dependency>
  <groupId>${project.groupId}</groupId>
  <artifactId>schema-iso19115-3</artifactId>
  <version>${project.version}</version>
</dependency>
Add the module to the webapp in web/pom.xml:

<execution>
  <id>copy-schemas</id>
  <phase>process-resources</phase>
  ...
  <resource>
    <directory>${project.basedir}/../schemas/iso19115-3/src/main/plugin</directory>
    <targetPath>${basedir}/src/main/webapp/WEB-INF/data/config/schema_plugins</targetPath>
  </resource>"

Build Failure Report
[INFO] ------------------------------------------------------------------------
[INFO] Building GeoNetwork schema plugin for ISO19115-3 standard 3.3.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ schema-iso19115-3 ---
[INFO] Deleting /Users/scgordon/core-geonetwork/schemas/iso19115-3/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ schema-iso19115-3 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- jrebel-maven-plugin:1.1.5:generate (generate-rebel-xml) @ schema-iso19115-3 ---
[INFO] Processing org.geonetwork-opensource:schema-iso19115-3 with packaging jar
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ schema-iso19115-3 ---
[INFO] Compiling 2 source files to /Users/scgordon/core-geonetwork/schemas/iso19115-3/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/scgordon/core-geonetwork/schemas/iso19115-3/src/main/java/org/fao/geonet/schema/iso19115_3/ISO19115_3SchemaPlugin.java:[23,7] error: ISO19115_3SchemaPlugin is not abstract and does not override abstract method getCswTypeNames() in CSWPlugin
[ERROR] /Users/scgordon/core-geonetwork/schemas/iso19115-3/src/main/java/org/fao/geonet/schema/iso19115_3/ISO19115_3SchemaPlugin.java:[44,8] error: constructor SchemaPlugin in class SchemaPlugin cannot be applied to given types;
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] GeoNetwork opensource .............................. SUCCESS [  0.344 s]
[INFO] common utils ....................................... SUCCESS [  3.157 s]
[INFO] Caching xslt module ................................ SUCCESS [  0.113 s]
[INFO] ArcSDE module (dummy-api) .......................... SUCCESS [  0.160 s]
[INFO] GeoNetwork domain .................................. SUCCESS [  4.900 s]
[INFO] Oaipmh modules ..................................... SUCCESS [  0.221 s]
[INFO] GeoNetwork Events .................................. SUCCESS [  0.122 s]
[INFO] GeoNetwork schema plugins .......................... SUCCESS [  0.005 s]
[INFO] GeoNetwork schema plugins core ..................... SUCCESS [  0.151 s]
[INFO] GeoNetwork schema plugin for ISO19139/119 standards  SUCCESS [  0.168 s]
[INFO] GeoNetwork core .................................... SUCCESS [  5.401 s]
[INFO] GeoNetwork schema plugin for Dublin Core records retrieved by CSW SUCCESS [  0.021 s]
[INFO] GeoNetwork schema plugin for Dublin Core standard .. SUCCESS [  0.162 s]
[INFO] GeoNetwork schema plugin for ISO19110 standard ..... SUCCESS [  0.094 s]
[INFO] GeoNetwork schema plugin for ISO19115-3 standard ... FAILURE [  0.079 s]
[INFO] GeoNetwork CSW server .............................. SKIPPED
[INFO] GeoNetwork harvesters .............................. SKIPPED
[INFO] GeoNetwork health monitor .......................... SKIPPED
[INFO] GeoNetwork services ................................ SKIPPED
[INFO] Geonetwork Web Resources 4 Java .................... SKIPPED
[INFO] GeoNetwork INSPIRE Atom ............................ SKIPPED
[INFO] Solr module ........................................ SKIPPED
[INFO] Solr core configuration ............................ SKIPPED
[INFO] Solr proxy ......................................... SKIPPED
[INFO] messaging .......................................... SKIPPED
[INFO] workers ............................................ SKIPPED
[INFO] WFS features harvester ............................. SKIPPED
[INFO] Tests for schema plugins ........................... SKIPPED
[INFO] GeoNetwork user interface module ................... SKIPPED
[INFO] JS API and Service documentation ................... SKIPPED
[INFO] GeoNetwork Web module .............................. SKIPPED
[INFO] GeoNetwork E2E Javascript Tests .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.590 s
[INFO] Finished at: 2017-01-04T12:19:54-07:00
[INFO] Final Memory: 87M/783M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project schema-iso19115-3: Compilation failure: Compilation failure:
[ERROR] /Users/scgordon/core-geonetwork/schemas/iso19115-3/src/main/java/org/fao/geonet/schema/iso19115_3/ISO19115_3SchemaPlugin.java:[23,7] error: ISO19115_3SchemaPlugin is not abstract and does not override abstract method getCswTypeNames() in CSWPlugin
[ERROR] /Users/scgordon/core-geonetwork/schemas/iso19115-3/src/main/java/org/fao/geonet/schema/iso19115_3/ISO19115_3SchemaPlugin.java:[44,8] error: constructor SchemaPlugin in class SchemaPlugin cannot be applied to given types;

**Comment by fxprunayre** [comment]
Could you check that your using branch 3.2.x for both the plugin (https://github.com/metadata101/iso19115-3/tree/3.2.x) and GeoNetwork (https://github.com/geonetwork/core-geonetwork/tree/3.2.x) ?

**Comment by scgordon** [comment]
Thanks François! The plugin as well as the ingest xsl is now working on my machine! Many thanks for the quick response.
