### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by AlexZeller** [metadata101/iso19115-3#36]
I'm trying to add the iso19115-3 schema plugin, following the instruction in the Readme. I've added the plugin in the schema folder and changed the pom.xml in the schema and web folder. When building I get the following error:

`
[ERROR] Failed to execute goal on project schema-core: Could not resolve dependencies for project org.geonetwork-opensource:schema-core:jar:3.4: Failure to find org.geonetwork-opensource:common:jar:3.4.4-SNAPSHOT in https://raw.githubusercontent.com/geonetwork/core-maven-repo/master was cached in the local repository, resolution will not be reattempted until the update interval of core-maven-repo has elapsed or updates are forced -> [Help 1]
`

Both the Plugin and Geonetwork are on branch 3.4.x.

Thanks for any advice.

**Comment by fxprunayre** [comment]
I can't reproduce, could you check the config. It looks even not related to iso19115-3 plugin has the error is between schema-core and common module. Update to 3.4.x latest branch - you maybe did a checkout during the release process last week and get a mix of version number. You should not be on 3.4.5-SNAPSHOT

```diff
$ git branch
* 3.4.x
$ git diff web/pom.xml schemas/pom.xml
diff --git a/schemas/pom.xml b/schemas/pom.xml
index a042aedec1..d75cd9acd3 100644
--- a/schemas/pom.xml
+++ b/schemas/pom.xml
@@ -51,6 +51,7 @@
     <module>dublin-core</module>
     <module>iso19110</module>
     <module>iso19139</module>
+    <module>iso19115-3</module>
   </modules>
   <properties>
     <rootProjectDir>../..</rootProjectDir>
diff --git a/web/pom.xml b/web/pom.xml
index 637bd9db1d..a806ee1cb6 100644
--- a/web/pom.xml
+++ b/web/pom.xml
@@ -504,6 +504,11 @@
       <artifactId>schema-iso19139</artifactId>
       <version>${gn.schemas.version}</version>
     </dependency>
+    <dependency>
+      <groupId>${project.groupId}</groupId>
+      <artifactId>schema-iso19115-3</artifactId>
+      <version>${gn.schemas.version}</version>
+    </dependency>
     <dependency>
       <groupId>${project.groupId}</groupId>
       <artifactId>schema-iso19110</artifactId>
@@ -729,6 +734,11 @@
                   <targetPath>${basedir}/src/main/webapp/WEB-INF/data/config/schema_plugins
                   </targetPath>
                 </resource>
+                <resource>
+                  <directory>${project.basedir}/../schemas/iso19115-3/src/main/plugin</directory>
+                  <targetPath>${basedir}/src/main/webapp/WEB-INF/data/config/schema_plugins
+                  </targetPath>
+                </resource>
                 <resource>
                   <directory>${project.basedir}/../schemas/iso19110/src/main/plugin</directory>
                   <targetPath>${basedir}/src/main/webapp/WEB-INF/data/config/schema_plugins
```

**Comment by AlexZeller** [comment]
Yes, you are right. I get the same Build Failure when trying to build the Application without adding the Plugin (Branch 3.4.x) so it's not related to the iso19115-3 plugin. 

I managed to get it working using the master branch of geonetwork and the 3.5.x branch of the plugin.

Thanks for your reply.
