### ISSUE TITLE
Missing gco.xsd

### ISSUE THREAD

**Issue by Delawen** [metadata101/iso19115-3#5]
I find that the gco.xsd file is missing from the repository. And that gives me issues on the form  java.nio.file.NoSuchFileException when trying to load it on a GeoNetwork 3 alpha. I am going to fix it locally and then check if I can merge here back (I am not using a 3.0.0 version and I am not sure if the problem is just me).

**Comment by fxprunayre** [comment]
Sorry forgot to commit https://github.com/metadata101/iso19115-3/commit/cc97b1bb14349cbada37be2fda243933c9e62f66

BTW, GN 3.0.0 also use the previous gco namespace (https://github.com/geonetwork/core-geonetwork/commit/1b6a6af1167e14f7abee217301caf2c2e30254b2). Branch 3.0.x should be used.

**Comment by Delawen** [comment]
Good! I was trying to replicate that commit :) Thanks :dancer:
