### ISSUE TITLE
INSPIRE check in index fields file looks wrong

### ISSUE THREAD

**Issue by josegar74** [metadata101/iso19115-3#7]
@fxprunayre , the INSPIRE parameter in the following file is defined as boolean:

https://github.com/metadata101/iso19115-3/blob/develop/src/main/plugin/iso19115-3/index-fields/common.xsl#L38

but the Java code sends the string value of the boolean (https://github.com/geonetwork/core-geonetwork/blob/develop/core/src/main/java/org/fao/geonet/kernel/search/SearchManager.java#L1258)

The following code always succeeds, causing an error later if the inspire thesaurus is not loaded:

https://github.com/metadata101/iso19115-3/blob/develop/src/main/plugin/iso19115-3/index-fields/common.xsl#L281

In other schemas the check is a bit different:

https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl#L33
https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl#L248

Maybe can be done in this schema a cast from string to boolean in xslt to fix this? Not sure whats the best solution.

**Comment by fxprunayre** [comment]
Probably use the same as iso19139. Can you take care of this ?
