### ISSUE TITLE
Save space for dateType fields

### ISSUE THREAD

**Issue by fxprunayre** [metadata101/iso19115-3#8]
Instead of having one line for the date and one for the datetype

![image](https://cloud.githubusercontent.com/assets/1701393/7773940/f5c614f0-00a7-11e5-8dc8-eb80b9edf634.png)

use online layout 

![image](https://cloud.githubusercontent.com/assets/1701393/7773917/cdb432bc-00a7-11e5-8912-4246b24fc056.png)

**Comment by Delawen** [comment]
Like this a lot!
